# Generated by Django 2.0 on 2018-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Event')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
            ],
        ),
    ]
