# Generated by Django 2.0 on 2018-10-24 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='date_from',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Slots'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_from',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_to',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=200, verbose_name='Venue'),
        ),
    ]
